name: Tests
on:
  push:
    branches: [main-ci]
  pull_request:
    branches: [master]
    types: [opened, reopened, updated, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: projectserum/build:v0.24.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install Node dependencies
        run: yarn install
      - name: Create a new Solana keypair
        run: solana-keygen new -s --no-bip39-passphrase
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: anchor test  --provider.cluster localnet
